### ISSUE TITLE
CSI 2.11 GA checklist

### ISSUE THREAD

**Issue by hemalathagajendran** [IBM/ibm-spectrum-scale-csi#1135]
## IBM Storage Scale CSI Driver GA release Checklist

- [x]  Doc updates (CSI/Scale/k8s docs) - All
- [x] Verify GitHub and IBM doc links are working (except 2.11.0 tag related links/commands) - Badri - 23rd Apr
- [x]  Update driver and operator SHAs when images are finalized - Hemalatha - 24th Apr
- [x]  Verify IBM doc links are working (including 2.11.0 tag related links and commands) - Shrutika - 26th Apr
- [x]  Final verification of doc changes - All - 24th Apr

Testing

- [x]  Realworld test complete 
- [x]  Regression complete - Abhishek/Saurabh - 24th Apr
- [x]  Regression on power9 for limited support - Saurabh - 24th Apr
- [x]  Verify the images and yaml from release branch are correct - on OCP cluster - CLI install - Saurabh - 26th Apr
- [x] Verify the images and yaml from release branch are correct - on k8s cluster - CLI install/Upgrade - Saurabh - 26th Apr

Cloudpak - Abhishek

- [x]  Check images for vulnerabilities(driver, operator, sidecars) - 25th Apr
- [x]  Create case bundle for Cloudpak certification - 25th Apr
- [x]  Cloudpak certification (content promotion ticket, release PR, verify image digest) - 25th Apr
- [x]  Publish cloudpak certification - 26th Apr

Release work - Hemalatha

- [x]  Create Golden Master images on quay 
- [x]  Push images to ICR staging and artifactory - GM and final release images 
- [x]  Pause dev checkin once stop-ship phase starts
- [x]  Create git release tag (draft) with release content (1 week before GA) - 23rd Apr
- [x]  Swap to ICR production - 25th Apr
- [x]  Verify images are getting pulled from ICR production - 25th Apr
- [x]  Merge dev into master (on GA date) - 25th Apr
- [x]  Push multi arch images to quay (on GA date) - 25th Apr
- [x]  Quay image tagging and updating quay image tags/SHAs in CSI 'dev' branch - 25th Apr
- [ ]  Publish git tag (on GA date) - 26th Apr
