### ISSUE TITLE
CSI 2.13 Release Checklist

### ISSUE THREAD

**Issue by hemalathagajendran** [IBM/ibm-spectrum-scale-csi#1251]
## IBM Storage Scale CSI Driver GA release Checklist
- [x]  CSI snap works on Vanila k8s
- [x]  Verify GitHub links are working - Shrutika
- [x]  Verify IBM docs links are working - Shrutika
- [x]  Pause dev checkin once stop-ship phase starts - All
- [x]  Create Golden Master images on quay (Atleast 1 week before GA) - Hemalatha
- [x]  Regression Complete - Saurabh
- [x]  Realworld test complete 
- [x]  Check images for Vulnerabilities(Driver, Operator, sidecars) 
- [x]  IBM Docs Content Verification (1 week before GA) - All 
- [x]  Create git release tag (draft) with release content (1 week before GA)- Hemalatha
- [x]  Merge dev into master (on GA date) - Hemalatha
- [x]  Push multi arch images to quay (on GA date) - Hemalatha
- [x]  Publish git tag (on GA date) - Hemalatha
- [x]  Verify the images and yaml from release branch are correct - CLI install/Upgrade (on GA date) - Saurabh
- [x]  Update driver listing https://kubernetes-csi.github.io/docs/drivers.html - Not Required

**Comment by hemalathagajendran** [comment]
Done
