### ISSUE TITLE
Cert Checklist

### ISSUE THREAD

**Issue by mew2057** [IBM/ibm-spectrum-scale-csi#36]
# Checklist

> **{Check #} [{Catalog Min}, {Certified}]** : {Condition}

Key | Action
-- | --
R | Required
A | If Applicable
P | Preferred
'' | Optional

## 1. Production Grade Config and Topology
- [x] **﻿1.1 [,R]**   : Does your workload follow best practices for running the respective product in a real-life production environment ?
- [x] **1.2 [,R]**   : Does your workload maintain docker images on a frequent timeline consistent with other non-container product deliveries ? 
- [x] **1.3 [,R/A]**   : Does your workload manage persistent volumes correctly, to avoid loss of data when pods are re-scheduled when disruptions and recovery occurs ?
- [ ] **1.4 [,R/A]**   : Does your workload provide clients with backup/recovery and DR data procedures ? 
- [ ] **1.5 [P,P]**   : Does your workload support Multi-Architectures (intel, power, z) ? 
- [ ] **1.6 [P,P]**   : Does your workload support Portability for IKS and ICP ?
- [ ] **1.7 [,P]**   : Does your workload provide a way to list, provision and bind your workload to other consumers/services without needing detailed knowledge of how your workload is created or managed ? 
- [x] **1.8 [,R/A]**   : Does your workload provide RedHat OpenShift Certified Operators to deploy and / or manage instances of your workload ?
- [x] **1.9 [R/A,R/A]**   : Does your Operator embed your existing helm chart  ?
- [ ] **1.10 [R/A,R/A]**  : Do all of the resources deployed via your operator meet our existing certification guidelines ?
- [ ] **1.11 [R/A,R/A]**  : Do all of the resources that deploy your operator and CRD’s meet our existing certification guidelines ?
- [ ] **1.12 [R/A,R/A]**  : If you have an ansible based operator, do all of the k8s jinja templates meet our existing certification guidelines?

## 2.  Self Healing / Automatic Failover

- [x] **2.1 [,R/A]**   : Does your workload support multiple active replicas (same image individually addressable) ?
- [x] **2.2 [,R/A]**   : Does your workload manage networking topologies that intelligently route requests when recovery/disruption occurs ? 
- [x] **2.3 [R ,R]**   : Does your workload monitor its health and understand how it reacts to these events ?
- [x] **2.4 [,P/A]**   : Does your workload monitor support and active/standby failover model and have you made it work in a native Kubernetes method ?

## 3. Self Healing / Automatic Failover

- [x] **3.1 [,R/A]**   : Does your workload consider controlling scheduling of the pods to ensure maximum resiliency ?
- [x] **3.2 [,R]**   : Does your workload test for resiliency ?
- [x] **3.3 [,R]**   : Does your workload test for performance ?
- [ ] **3.4 [,P]**   : Does your workload run in multiple failure zones in a single cluster ? 

## 4. Ability to scale up/down

- [ ] **4.1 [P,R]**   : Does your workload support being manually scaled to add instance transparent to the end user ?
- [ ] **4.2 [,P]**   : Does your workload support horizontal pod autoscaling ?
- [ ] **4.3 [,R/A]**   : Does your workload support scaling a StatefulSet (if using StatefulSets) ? Can you add members into the StatefulSet for a stateful workload without service interruption ?
- [ ] **4.4 [,R/A]**   : Does your workload controlled scale down ?
- [x] **4.5 [,R/A]**   : Does your workload support being deployed more than once in the same cluster 

## 5. Image Vulnerability Scanning / Mgmt

- [ ] **5.1 [R,R]**   : Does your workload manage all image vulnerabilities on an ongoing basis on the timelines established with the Product Security Incident Response Team (PSIRT) ? 
- [ ] **5.2 [R,R]**   : Does your workload ensure integration with the content CICD continuous scanning for vulnerabilities for ongoing visibility of image vulnerabilities ?
- [ ] **5.3 [R,P]**   : Does your workload ensure that if you are shipping images on Docker Hub (or any image repository) that the repository's vulnerability detector does not show critical exposures for your shipped images ?
- [x] **5.4 [P,R]**   : Does your workload deliver RedHat certified UBI based images ?

## 6. Limits Privileges/Context

- [ ] **6.1 [P,P]**   : Does your workload run with privileges that allow it to meet CIS controls ?
- [ ] **6.2 [R,R]**   : Does your workload require elevated (non-CIS compliant) privileges and deliver security policies to run the workload with the least privilege required ?

## 7. Secure Access Considerations

- [x] **7.1 [R,R]**   : Does your workload require special user privileges to install (team admin or cluster admin) ?
- [x] **7.2 [P,R]**   : Does your workload ensure fine grained separation of roles for admin activities vs operator activities ?
- [x] **7.3 [P/R,R]**   : Does your workload avoid exposing sensitive information in the Helm Release ?
- [x] **7.4 [,R/A]**   : Does your workload use TLS for encryption in motion ?
- [ ] **7.5 [,P]**   : Does your workload have the ability to operate using customer certificates ?
- [x] **7.6 [,R/A]**   : Does your workload support the ability to have encryption at rest if required by a customer ?
- [x] **7.7 [P, R]**   : Does your workload support provide authentication / authorization ?
- [ ] **7.8 [,P]**   : Does your workload provide audit capabilities for data access ?
- [ ] **7.9 [R/A,R/A]**    : Does your Operator support being configured with different scopes  ?

## 8. BISO Compliance

- [ ] **8.1 [P/R,R]**   : Does your workload follow the Secure Release process ?

## 9. Upgrade/Rollback Using Platform Experience

- [ ] **9.1 [P,R]**   : Does your workload use the platform functions in the UI to upgrade and rollback all charts ?
- [ ] **9.2 [P,R]**   : Does your workload test Upgrades prior to shipment and validate that your release notes match the upgrade support from version to version ?
- [ ] **9.3 [,R]**   : Does your workload support non-disruptive rolling upgrades within patch/minor release levels ?

## 10. Standard Version Management

- [x] **10.1 [R,R]**   : Does your workload honor and follow the helm chart sem-version standard ?
- [x] **10.2 [R,R]**   : Does your workload maintain your docker versions / tags separate from the Helm Chart version ?

## 11. Maintain Consistency/Consumability Guidelines

- [ ] **11.1 [R,R]**   : Does your workload deliver all content to the content CICD and compatiblity before a chart is shipped ? 
- [ ] **11.2 [R,R]**   : Does your workload adhere to the Linter recommendations for both errors and warnings and address them for each product shipment ?
- [ ] **11.3 [R,R]**   : Does your workload make the updates as recommended by the content squad focal based on the code reviews or PRs to merge the code ?
- [x] **11.4 [R/A,R/A]**   : Does your workload provide Operators packaged as part of a CASE bundle ?

## 12. Maintain Content Currency with Versions (kube/helm/platform)

- [ ] **12.1 [R,R]**   : Does your workload stay current with the Platform and ensure it supports each release within 30 days of the platform GA ?
- [ ] **12.2 [R,R]**   : Does your workload deliver regular releases of helm content every 120 days or less ?

## 13. Integration with Catalog Experience

- [ ] **13.1 [R,R]**   : Does your workload use the platform catalog features such as metadata, keywords, release notes, launch links, readme conventions, etc.. visible in the platform UI ?
- [ ] **13.2 [R,R]**   : Does your workload have a "consumable" experience in the platform catalog UI deployment process ?
- [ ] **13.3 [P,R/A]**   : Does your workload ensure all resources that your workload deploys (for embedded helm charts/objects) are associated together via helm-releases or tied information ?

## 14. Integration with Logging Service

- [x] **14.1 [,R]**   : Does your workload output logs to standard out for consumption by the platform common service ? 
- [ ] **14.2 [,P/A]**   : Does your workload deliver custom Kibana dashboards that are personalized for custom logging of your workload ?

## 15. Integration with Monitoring Service

- [ ] **15.1 [,P]**   : Does your workload support workload specific monitoring enabled in the platform common service ? 
- [ ] **15.2 [,P/A]**   : Does your workload deliver custom Grafana dashboards that are personalized for custom monitoring of your workload ?

## 16. Integration with Metering Services

- [ ] **16.1 [R,R]**   : Does your workload use the mandatory metering annotations ? 
- [ ] **16.2 [,]**   : Does your workload use custom metering metrics ? 

## 17. Use production/supported Helm/Kube features

- [x] **17.1 [P,R]**   : Does your workload avoid use of alpha functions ? 
- [ ] **17.2 [R,R]**   : Does your workload avoid using hard-coded kubernetes capabilities by "version" , e.g. kubernetes 1.8 ? 

## 18. Full Sack Compatibility Verification

- [ ] **18.1 [ R,R]**   : Does your workload maintain current code in the compatibility Testing in synch with PPA and FixCentral shipments ?
- [ ] **18.2 [ R,R]**   : Does your workload provide Content Verification Tests (cv-tests) to insure your Chart installs, runs, and cleans up the workload in the compatibility test environments ?

## 19. Multiple Configuration Testing

- [ ] **19.1 [ P,R]**   :  Does your workload have multiple CV Tests that are built to exercise your chart and workload for multiple configurations and use cases ?
- [ ] **19.2 [ R,R]**   : Does your workload deploy both from the CLI and from the Platform Catalog User Experience ?
- [ ] **19.3 [ R,R]**   : Does your workload test on ALL platforms identified in the Chart.yaml keywords file? 

## 20. Ship End User License Displayable in Catalog

- [x] **20.1 [R,R]**   : Does your workload have the Product License/s available in the helm chart and viewable in the Catalog ? 
- [x] **20.2 [R,R]**   : Does product license in your docker image match your helm chart product license ? 

## 21. On-boarded to the Integrated Support Processes

- [x] **21.1 [ R/A,R/A]**   : Does your workload follow the ICP support processes ?
- [x] **21.2 [ R/A,R/A]**   : Does your workload follow the IBM Public Cloud support processes ?

**Comment by mew2057** [comment]
closing, moved to cert tool.
