### ISSUE TITLE
CSI 2.2.0 release checklist

### ISSUE THREAD

**Issue by deeghuge** [IBM/ibm-spectrum-scale-csi#394]
IBM Spectrum Scale CSI Driver v2.2.0 release Checklist 

- [x] Switch ImagePullPolicy 
- [x] csi snap works on Vanila k8s, Openshift with and without OLM deployment
- [x] Verify the GitHub and KC links are working
- [x] Pause dev checkin once stop-ship phase starts
- [x] Create Golden Master (Atleast 1 week before GA)
- [x] Regression Complete
- [x] OLM Packages Ready and Tested
- [x] Generate Red hat bundle - code changes only
- [x] Red hat bundle - Upload images for scanning
- [x] Red hat bundle - Upload bundle for scanning - Do not Publish
- [x] Check images for Vulnerabilities(Driver, Operator, sidecars)
- [x] Final KC Verification (1 week before GA)
- [x] Create git tag draft with release content  (1 week before GA)
- [x] Merge dev into master (on GA date)
- [x] Push multi arch images to quay (on GA date)
- [x] Publish git tag (on GA date)
- [x] Verify the images and yaml from release branch are correct - CLI install/Upgrade (on GA date)
- [x] Create PR for Community Operator Listing (on GA date) - Directory to update "upstream-community-operators"
- [x] Create PR for Community Operator Listing after "upstream-community-operators" PR is merged- Directory to update "community-operators"
- [x] Publish Red Hat registry bundle
- [x] Update driver listing https://kubernetes-csi.github.io/docs/drivers.html
- [x] Unpause dev checkin. (once OLM is verified for community operator)
- [x] Switch ImagePullPolicy to Always

**Comment by madhuthorat** [comment]
Verify the GitHub links are working  - Done.

**Comment by smitaraut** [comment]
Created Golden master images-
quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-operator:v2.2-GM1
quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-driver:v2.2-GM1

**Comment by kulkarnicr** [comment]
These are two PR for Community Operator Listing-
https://github.com/operator-framework/community-operators/pull/3666
https://github.com/operator-framework/community-operators/pull/3671

**Comment by deeghuge** [comment]
IBM Spectrum Scale CSI Driver v2.2.0 is successfully released.
https://github.com/IBM/ibm-spectrum-scale-csi/releases/tag/v2.2.0
quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver:v2.2.0
quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-operator:v2.2.0
https://operatorhub.io/operator/ibm-spectrum-scale-csi-operator
https://catalog.redhat.com/software/containers/ibm/ibm-spectrum-scale-csi-operator-bundle/5f7f4b1169aea3467fdceb9d
https://kubernetes-csi.github.io/docs/drivers.html
