### ISSUE TITLE
IBM Spectrum Scale CSI Driver v2.3.1 PTF release Checklist

### ISSUE THREAD

**Issue by madhuthorat** [IBM/ibm-spectrum-scale-csi#499]
IBM Spectrum Scale CSI Driver v2.3.1 PTF release Checklist

- [x]  csi snap works on Vanila k8s, Openshift with and without OLM deployment - Abhishek/Vrushal - 14 Oct
- [x]  Verify the GitHub links are working including README links - Amol - 14 Oct and 22 Oct
- [x]  Verify KC links are working - Amol co-ordinate with Ranjit - 14 Oct and 22 oct
- [x]  Pause dev checkin once stop-ship phase starts - Madhu - Done
- [x]  Create Golden Master images on quay (Atleast 1 week before PTF) - Madhu (backup Deepak if Madhu doesn’t get access) - 14 Oct
- [x]  Regression Complete - Abhishek - 14 Oct
- [x]  RW test complete - 14 Oct
- [x]  OLM Packages Ready and Tested - Abhishek - 14 Oct
- [x]  Generate Red hat bundle - code changes only - Abhishek, Madhu (will verify code). - 14 Oct
- [x]  Red hat bundle - Upload images for scanning - Deepak. (Get access for all.) - 14 Oct
- [x]  Red hat bundle - Upload bundle for scanning - Do not Publish - Deepak. Get access for all. (atleast 1 week before GA) - 14 Oct
- [x]  Check images for Vulnerabilities(Driver, Operator, sidecars) - Vrushal/Abhishek - 14 Oct
- [x]  Final KC Verification (1 week before PTF) - All - 14 Oct and 19 Oct
- [x]  Create git tag draft with release content (1 week before PTF) - Madhu - Done
- [x]  Merge dev into master (on PTF date) - Madhu - 22 Oct
- [x]  Push multi arch images to quay (on PTF date)- Madhu (backup Deepak if Madhu doesn’t get access). - 22 Oct
- [x]  Publish git tag (on PTF date) - Madhu. - 22 Oct
- [x]  Verify the images and yaml from release branch are correct - CLI install/Upgrade (on PTF date) - Vrushal - 22 Oct
- [x]  Create PR for Community Operator Listing (on PTF date) - Directory to update "upstream-community-operators" - Abhishek - 20 Oct
- [x]  Create PR for Community Operator Listing after "upstream-community-operators" PR is merged- Directory to update "community-operators" - Abhishek - 20 Oct
- [ ]  Publish Red Hat registry bundle - Deepak - 22 Oct - **This won't be done as we have to stop publishing to Redhat registry bundle. Last publish was for CSI v2.2.0**
- [x]  Update driver listing https://kubernetes-csi.github.io/docs/drivers.html - Madhu - 20 Oct
- [x]  Unpause dev checkin. (once OLM is verified for community operator) - Madhu - 22 Oct
- [x]  For 2.3.1: Incremental cloudpak certification, create case bundle, raise PR - update digest - Abhishek - 14 Oct
- [x]  For 2.3.1: Publish cloudpak certification - Abhishek - 22 Oct
- [x]  Image for ICR push - Deepak - for GM images and final release images. - 20 and 22 Oct

**Comment by madhuthorat** [comment]
- csi snap works on Vanila k8s, Openshift with and without OLM deployment - Abhishek/Vrushal ?
- Verify the GitHub and KC links are working - Amol
- Pause dev checkin once stop-ship phase starts - Madhu
- Create Golden Master (Atleast 1 week before PTF) - Madhu/Deepak - get access to Tekton from Evan/Laura 
- Regression Complete - Abhishek
- RW testing - Tristan
-  OLM Packages Ready and Tested - Abhishek
- Generate Red hat bundle - code changes and code verification - Abhishek, Madhu (verify code).
- Red hat bundle - Upload images for scanning - Deepak. Get access for all.
- Red hat bundle - Upload bundle for scanning - Do not Publish - Deepak. Get access for all. (atleast 1 week before GA)
-  Check images for Vulnerabilities(Driver, Operator, sidecars) - Anyone
- Final KC Verification (1 week before PTF) - All
- Create git tag draft with release content (1 week before PTF) - Madhu
- Merge dev into master (on PTF date) - Madhu
- Push multi arch images to quay (on PTF date) - Get tekton access - Madhu/Deepak.
- Publish git tag (on PTF date) - Madhu.
- Verify the images and yaml from release branch are correct - CLI install/Upgrade (on PTF date) - Vrushal
- Create PR for Community Operator Listing (on PTF date) - Directory to update "upstream-community-operators" - Abhishek
- Create PR for Community Operator Listing after "upstream-community-operators" PR is merged- Directory to update "community-operators" - Abhishek
