### ISSUE TITLE
CSI 2.4.0 GA Checklist

### ISSUE THREAD

**Issue by madhuthorat** [IBM/ibm-spectrum-scale-csi#532]
IBM Spectrum Scale CSI Driver v2.4.0 GA release Checklist

- [x]  csi snap works on Vanila k8s, Openshift with and without OLM deployment - Abhishek/Vrushal/Monica - 2 Dec
- [x]  Verify the GitHub links are working including README links - Nitish - 2 Dec and 10 Dec
- [x]  Verify KC links are working - Amol co-ordinate with Ranjit - 2 Dec and 10 Dec
- [x]  Pause dev checkin once stop-ship phase starts - Madhu - 26 Nov
- [x]  Create Golden Master images on quay (Atleast 1 week before GA) - Madhu (backup Deepak if Madhu doesn’t get access) - 2 Dec
- [x]  Regression Complete - Abhishek - 2 Dec
- [x]  RW test complete - 2 Dec
- [x]  OLM Packages Ready and Tested - Abhishek - 2 Dec
- [x]  Check images for Vulnerabilities(Driver, Operator, sidecars) - Vrushal/Abhishek - 2 Dec
- [x]  Final KC Verification (1 week before GA) - All - 2 Dec and 7 Dec
- [x]  Create git tag draft with release content (1 week before GA) - Madhu - 29 Nov
- [x]  Merge dev into master (on GA date) - Madhu - 10 Dec
- [x]  Push multi arch images to quay (on GA date)- Madhu (backup Deepak if Madhu doesn’t get access). - 10 Dec
- [x]  Publish git tag (on GA date) - Madhu. - 10 Dec
- [x]  Verify the images and yaml from release branch are correct - CLI install/Upgrade (on GA date) - Vrushal - 10 Dec
- [x]  Create PR for Community Operator Listing (on GA date) - Directory to update "upstream-community-operators" - Abhishek - 10 Dec
- [x]  Create PR for Community Operator Listing after "upstream-community-operators" PR is merged- Directory to update "community-operators" - Abhishek - 8 Dec
- [x]  Update driver listing https://kubernetes-csi.github.io/docs/drivers.html - Madhu - 8 Dec
- [x]  Unpause dev checkin. (once OLM is verified for community operator) - Madhu - 10 Dec
- [x]  For 2.4.0: Incremental cloudpak certification, create case bundle, raise PR - update digest - Abhishek - 2 Dec
- [x]  For 2.4.0: Publish cloudpak certification - Abhishek - 10 Dec
- [x]  Image for ICR push - Deepak - for GM images and final release images. - 8 Dec and 10 Dec

**Comment by madhuthorat** [comment]
All tasks completed.
