### ISSUE TITLE
Go operator for CSI 2.5.0 ( early observations) 

### ISSUE THREAD

**Issue by Jainbrt** [IBM/ibm-spectrum-scale-csi#536]
**Image Used :**
`(for x86): quay.io/madhuthorat/ibm-spectrum-scale-csi-operator-dev:goop311221`

**Early Observations for go operator testing**

1. [x] <del> Clusterroles name are not same </del>
2. [x] <del>  Clusterrules rules are not same i.e. attacher clusterrole </del> 
3. [x] <del> csi psp for k8s/OCP env not working </del> 
4. [x] <del>  Clusterrolebinding name are not same </del> 
5. [x] <del> Clusterrole and clusterrolebindig for node plugin is not present <del>
6. [x] Reconciler is restarting all the pods, even we change plugin selector label ( might need improvement as discussed)
7. [x] <del> New labels are not getting refelected in statefuleset pods ( if we change the labels and reapply the cr for statefulset pods ) <del>
8. [x] <del> CSI CR status ( Reconciliation, Installation, Running etc..) <del>
9. [x] "/var/lib/kubelet/plugins/spectrumscale.csi.ibm.com/" is not getting cleaned up after driver uninstall - **Not a defect, same behavior as ansible operator.** However tracked as an enhancement in #544 
10. [x] <del> ibm-spectrum-scale-csi-resizer-0 shows two containers <del>
11. [x] <del> when we change secret username and password , Its not getting picked up by driver pods </del>
12. [x] <del> changing LIVENESS_HEALTH_PORT in env is not changing healthport </del>
13. [x]  <del>  imagePullSecrets in cr file is not working </del>
14. [x] <del> Include CSI operator release version in operator logs **- Not a defect, ansible doesn't support this.** We added in Go operator this change. <del>
15. [x] Need to review duplicate clusterrole rules in operator.yaml - **Not a defect, as Go operator is having same rules as ansible**. Considering this in issue #544 
16. [x]  <del> primayFS parameter change does not restart the driver pods  <del>
17. [x]  <del>remove references for ansible operator from go operator.yaml file   <del>
18. [x] Go operator debug log level from operator yaml file  **- Not a defect, check issue #544 for more details.**
19. [x]   <del>OLM install/upgrade support on k8s & OCP both  <del>
20. [x] Secret check is required in the namespace, before creating statefulsets for sidecar containers - Secret creation is pre-req as per KC, without it behavior is undefined. Even though statefulsets are created they are of no use, as seen the driver is not usable with Go operator so this should be ok. **Not a defect.** Considering it in issue #544.

**Comment by vrushch** [comment]
- [ ] when we change secret username and password , Its not getting picked up by driver pods
- [ ] changing LIVENESS_HEALTH_PORT  in env is not changing healthport 


for recreating secret change scenario
```
1. Deploy operator and driver
2. Edit secret parameters
3. check in driver pod logs , its still using old username for communicating
```

**Comment by vrushch** [comment]
- [ ]  imagePullSecrets in cr file is not working

**Comment by madhuthorat** [comment]
- [ ] Clusterroles name are not same - Amol
- [ ]  Clusterroles rules are not same i.e. attacher clusterrole - Amol
- [ ]  csi psp for k8s/OCP env not working - Amol
- [ ]  Clusterrolebinding name are not same - Amol
- [ ]  Clusterrole and clusterrolebindig for node plugin is not present - Amol
- [ ]  Reconciler is restarting all the pods, even we change plugin selector label ( might need improvement as discussed) - Nitish
- [ ]  New labels are not getting refelected in statefuleset pods ( if we change the labels and reapply the cr for statefulset pods ) - Nitish
- [ ]  CSI CR status ( Reconciliation, Running etc..) - Nitish
- [ ]  CSI CR reconciliation failure reason in CR status - Nitish
- [ ]  CSI CR installation failure reason in CR status - Nitish
- [ ]  when we change secret username and password , Its not getting picked up by driver pods - Nitish
- [ ]  changing LIVENESS_HEALTH_PORT in env is not changing healthport - Madhu
- [ ]  imagePullSecrets in cr file is not working - Madhu

**Comment by nitishkumar4** [comment]
Few updates:

**For "Reconciler is restarting all the pods, even we change plugin selector label"**
Status:  WIP
PR raised https://github.com/madhuthorat/ibm-spectrum-scale-csi/pull/29

**For "New labels are not getting refelected in statefuleset pods "**
Status:  Closed
New labels are updated in statefulset, however if the statefulset pod is in pending state, then the pod doens't pick the change unless pod is manually deleted.
This is default kubernetes behavior and also the behaviour is same as in case of ansible operator.
Reference: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/ Rolling updates section.

**CSI CR status ( Reconciliation, Running etc..)**
Status: Closed
As discussed, this is needed as an enhancement, added the requirement to the enhancement list.
Boxnote: https://ibm.ent.box.com/notes/888037421218?s=x2rt7667u20bu43e1prf9x6bsrmgj9vv

**CSI CR reconciliation failure reason in CR status**
**CSI CR installation failure reason in CR status**
Status: WIP
PR raised https://github.com/madhuthorat/ibm-spectrum-scale-csi/pull/28

**when we change secret username and password , Its not getting picked up by driver pods**
Status: WIP
PR rasied https://github.com/madhuthorat/ibm-spectrum-scale-csi/pull/29

**Comment by madhuthorat** [comment]
CSI CR status ( Reconciliation, Running etc..) - Nitish - Test on both k8s and OCP.
 CSI CR reconciliation failure reason in CR status - Nitish
 CSI CR installation failure reason in CR status - Nitish

The above 3 are single defect as all related to same thing.

Include CSI operator release version in operator logs - This is improvement, not a defect. Ansible operator doesn't show CSI operator release version

**Comment by madhuthorat** [comment]
All defects have been handled, some are enhancements and tracked in issue #544 
Please check.

**Comment by Jainbrt** [comment]
Closing this defect, we will raise new defects if there will be new findings going forwards.
