### ISSUE TITLE
IBM Spectrum Scale CSI 2.5.0 checklist

### ISSUE THREAD

**Issue by madhuthorat** [IBM/ibm-spectrum-scale-csi#653]
## IBM Spectrum Scale CSI Driver GA release Checklist

- [x]  CSI snap works with/without CG on Vanila k8s, Openshift with and without OLM deployment - Abhishek/Vrushal/Monica - 14 Mar
- [x]  Verify GitHub links are working - Nitish - 14 Mar and 29 Mar
- [x]  Verify IBM docs links are working - Amol co-ordinate with Teja - 14 Mar and 29 Mar
- [x]  Pause dev checkin once stop-ship phase starts - Madhu - 11 Mar
- [x]  Create Golden Master images on quay (Atleast 1 week before GA) - Madhu (backup Deepak) - 11 Mar
- [x]  Regression Complete - Abhishek, Sanjay - 14 Mar
- [x]  Realworld test complete - Tristan, Tom - 11 Mar
- [x]  OLM Packages Ready and Tested - Abhishek - 15 Mar
- [x]  Create case bundle for Cloudpak certification - Abhishek - 25 Mar
- [x]  Check images for Vulnerabilities(Driver, Operator, sidecars) - Vrushal - 17 Mar
- [x]  IBM Docs Content Verification (1 week before GA) - All - 25 Mar - 27 Mar
- [x]  Create git release tag (draft) with release content (1 week before GA) - Madhu - 24 Mar
- [x]  Merge dev into master (on GA date) - Madhu - 29 Mar
- [x]  Push multi arch images to quay (on GA date) - Madhu - 29 Mar
- [x]  Publish git tag (on GA date) - Madhu - 29 Mar
- [x]  Verify the images and yaml from release branch are correct - CLI install/Upgrade (on GA date) - Vrushal - 29 Mar
- [x]  Create PR in private repo for Redhat Community Operator Listing (https://github.com/redhat-openshift-ecosystem/community-operators-prod) - Abhishek - 24 Mar 
- [x]  Create PR in private repo for Community Operator Listing (https://github.com/k8s-operatorhub/community-operators) - Abhishek - 24 Mar
- [x]  Publish PR for Redhat Community Operator Listing (https://github.com/redhat-openshift-ecosystem/community-operators-prod) - (on GA date) - Abhishek - 29 Mar 
- [x]  Publish PR for Community Operator Listing (https://github.com/k8s-operatorhub/community-operators) - (on GA date) - - Abhishek - 29 Mar
- [x]  Update driver listing https://kubernetes-csi.github.io/docs/drivers.html - Amol - 27 Mar
- [x]  Unpause dev checkin. (once OLM is verified for community operator) - Madhu - 31 Mar
- [x]  Cloudpak certification (Content promotion ticket, Release PR, verify image digest) - Abhishek - 24 Mar
- [x]  Publish cloudpak certification - Abhishek - 16-Mar
- [x]  Image for ICR and artifactory push - GM and final release images - Madhu (Deepak backup) - 14-Mar and 16-Mar
- [x] Quay image tagging and updating quay image tags in CSI 'dev' branch - 29 Mar

**Comment by aspalazz** [comment]
@lostasi FYI

**Comment by madhuthorat** [comment]
All tasks completed !
