### ISSUE TITLE
IBM Spectrum Scale CSI 2.5.1 checklist

### ISSUE THREAD

**Issue by amdabhad** [IBM/ibm-spectrum-scale-csi#709]
## IBM Spectrum Scale CSI 2.5.1 GA release Checklist

- [x]  CSI snap works with/without CG on Vanila k8s, Openshift with and without OLM deployment - Abhishek/Vrushal/Monica - 29 Apr
- [x]  Verify GitHub links are working - Nitish - 4 May and 5 May
- [x]  Verify IBM docs links are working - Amol co-ordinate with Teja - 4 May and 5 May
- [x]  Pause dev checkin once stop-ship phase starts - Madhu - 22 Apr
- [x]  Create Golden Master images on quay (Atleast 1 week before GA) - Madhu (backup Deepak) - Not needed for 2.5.1
- [x]  Regression Complete - Abhishek, Sanjay - 29 Apr
- [x]  OLM Packages Ready and Tested - Abhishek - 2-4 May
- [x]  Create case bundle for Cloudpak certification - Abhishek - 4 May
- [x]  Check images for Vulnerabilities(Driver, Operator, sidecars) - Vrushal - 4 May
- [x]  IBM Docs Content Verification - All - 4-5 May
- [x]  Create git release tag (draft) with release content  - Madhu - 2-4 May
- [x]  Merge dev into master (on GA date) - Madhu - 5 May
- [x]  Push multi arch images to quay (on GA date) - Madhu - 5 May
- [x]  Publish git tag (on GA date) - Madhu - 5 May
- [x]  Verify the images and yaml from release branch are correct - CLI install/Upgrade (on GA date) - Vrushal - 5 May
- [x]  Create PR in private repo for Redhat Community Operator Listing (https://github.com/redhat-openshift-ecosystem/community-operators-prod) - Abhishek - 2-4 May
- [x]  Create PR in private repo for Community Operator Listing (https://github.com/k8s-operatorhub/community-operators) - Abhishek - 2-4 May
- [x]  Publish PR for Redhat Community Operator Listing (https://github.com/redhat-openshift-ecosystem/community-operators-prod) - (on GA date) - Abhishek - 5 May
- [x]  Publish PR for Community Operator Listing (https://github.com/k8s-operatorhub/community-operators) - (on GA date) - Abhishek - 5 May
- [x]  Update driver listing https://kubernetes-csi.github.io/docs/drivers.html - Amol - Not needed for 2.5.1
- [x]  Unpause dev checkin. (once OLM is verified for community operator) - Madhu - 6 May
- [x]  Cloudpak certification (Content promotion ticket, Release PR, verify image digest) - Abhishek - 2-4 May
- [x]  Publish cloudpak certification - Abhishek - 4 May
- [x]  Image for ICR and artifactory push - GM and final release images - Madhu (Deepak backup) - 4-5 May
- [x]  Quay image tagging and updating quay image tags in CSI 'dev' branch - 4-5 May

**Comment by Jainbrt** [comment]
As we are completed with all activities, so closing the issue.
