### ISSUE TITLE
Spectrum Scale CSI 2.6.0 checklist

### ISSUE THREAD

**Issue by amdabhad** [IBM/ibm-spectrum-scale-csi#737]
## IBM Spectrum Scale CSI Driver GA release Checklist

- [ ] CSI snap works with/without CG on Vanila k8s, Openshift with and without OLM deployment - Abhishek/Vrushal/Monica - 10 June
- [ ] Verify GitHub links are working - Nitish - 10 June and 23 June
- [ ] Verify IBM docs links are working - Nitish co-ordinate with Teja - 10 June and 23 June
- [ ] Pause dev checkin once stop-ship phase starts - Amol - 13 June
- [ ] Create Golden Master images on quay (Atleast 1 week before GA) - Amol (backup Deepak) - 16 June
- [ ] Regression Complete - Abhishek, Sanjay - 10 June
- [ ] Realworld test complete - Tristan, Tom - 10 June
- [ ] OLM Packages Ready and Tested - Abhishek - 10 June
- [ ] Create case bundle for Cloudpak certification - Abhishek - 19 June
- [ ] Check images for Vulnerabilities(Driver, Operator, sidecars) - Vrushal - 13 June
- [ ] IBM Docs Content Verification (1 week before GA) - All - 15 June - 17 June
- [ ] Create git release tag (draft) with release content (1 week before GA) - Amol - 16 June
- [ ] Merge dev into master (on GA date) - Amol - 23 June
- [ ] Push multi arch images to quay (on GA date) - Amol - 23 June
- [ ] Publish git tag (on GA date) - Amol - 23 June
- [ ] Verify the images and yaml from release branch are correct - CLI install/Upgrade (on GA date) - Vrushal - 23 June
- [ ] Create PR in private repo for Redhat Community Operator Listing (https://github.com/redhat-openshift-ecosystem/community-operators-prod) - Abhishek - 17 June
- [ ] Create PR in private repo for Community Operator Listing (https://github.com/k8s-operatorhub/community-operators) - Abhishek - 17 June
- [ ] Publish PR for Redhat Community Operator Listing (https://github.com/redhat-openshift-ecosystem/community-operators-prod) - (on GA date) - Abhishek - 23 June
- [ ] Publish PR for Community Operator Listing (https://github.com/k8s-operatorhub/community-operators) - (on GA date) - Abhishek - 23 June
- [ ] Update driver listing https://kubernetes-csi.github.io/docs/drivers.html - Not needed for 2.6.0
- [ ] Unpause dev checkin. (once OLM is verified for community operator) - Amol - 24 June
- [ ] Cloudpak certification (Content promotion ticket, Release PR, verify image digest) - Abhishek - 17-20 June
- [ ] Publish cloudpak certification - Abhishek - 22 June
- [ ] Image for ICR and artifactory push - GM and final release images - Amol (Deepak backup) - 9 June and 10 June
- [ ] Quay image tagging and updating quay image tags/SHAs in CSI 'dev' branch - Amol - 23 June

**Comment by Jainbrt** [comment]
All release tasks are completed.
