### ISSUE TITLE
CSI 2.7.0 GA Checklist

### ISSUE THREAD

**Issue by amdabhad** [IBM/ibm-spectrum-scale-csi#788]
## IBM Spectrum Scale CSI Driver GA release Checklist

1. [x] Verify GitHub links are working - Monica - 16 Sept and 28 Sept
2. [x] Verify IBM docs links are working  (including manifests in commands) - Ghanshyam - 16 Sept and 28 Sept
3. [x] Update versions (driver, operator, sidecars, upgrade pages, hardware and software requirements page, etc) in IBM docs - Saurabh - 16 Sept
4. [x] Pause dev checkin once stop-ship phase starts - Amol - 19 Sept
5. [x] Create Golden Master images on quay (Atleast 1 week before GA) - Amol (backup Deepak) - 22 Sept
6. [x] Regression Complete - Abhishek, Sanjay - 19 Sept
7. [x] Realworld test complete - Tristan, Tom - 19 Sept
8. [x] Create case bundle for Cloudpak certification - Abhishek - 23 Sept
9. [x] Check images for Vulnerabilities(Driver, Operator, sidecars) - Saurabh - 19 Sept
10. [x] IBM Docs Content Verification - All - 13-16 Sept
11. [x] Create git release tag (draft) with release content (1 week before GA) - Amol - 22 Sept
12. [x] Swap to ICR production -  (Reminder - to upload snapshotter v6.0.1) - Amol  - 26 Sept
13. [x] Verify images are getting pulled from ICR production - Amol - 26 Sept
14. [x] Merge dev into master (on GA date) - Amol - 28 Sept
15. [x] Push multi arch images to quay (on GA date) - Amol - 28 Sept
16. [x] Publish git tag (on GA date) - Amol - 28 Sept
17. [x] Verify the images and yaml from release branch are correct - on k8s - CSI install/Upgrade - Saurabh - 28 Sept
18. [x] Verify the images and yaml from release branch are correct - on OCP - CNSA install - Monica - 28 Sept
19. [x] Update driver listing https://kubernetes-csi.github.io/docs/drivers.html - Not needed for 2.7.0
20. [x] Unpause dev checkin - Amol - 29 Sept
21. [x] Cloudpak certification (Content promotion ticket, Release PR, verify image digest) - Abhishek - 22-23 Sept
22. [x] Publish cloudpak certification - Abhishek - 27 Sept
23. [x] Push Images to ICR staging and artifactory - GM and final release images - Amol (Deepak backup) - 16 Sept
24. [x] Quay image tagging and updating quay image tags/SHAs in CSI 'dev' branch - Amol - 28 Sept
25. [x] FAQ update via [RTC 122919](https://jazz07.rchland.ibm.com:21443/jazz/web/projects/GPFS#action=com.ibm.team.workitem.viewWorkItem&id=122919)  - Abhishek - 29 Sept
