### ISSUE TITLE
CSI 2.6.1 Checklist

### ISSUE THREAD

**Issue by amdabhad** [IBM/ibm-spectrum-scale-csi#798]
- [x] Create a 2.6.1 branch and cherry-pick the mount fixes - Amol - 13 Sept
- [x] Make 2.6.1 version changes - Amol - 13 Sept
- [x] Running tests on the build - Abhishek/Saurabh/Monica - 16 Sept
- [x] A PR for build delivery to CNSA (for CSI move form dev quay to prod quay) - Amol - 19 Sept
- [x] CloudPak certification - Abhishek - 21 Sept
- [x] Pushing images to ICR, artifactory, quay production repo - Amol - 22 Sept 
- [x] Create and publish 2.6.1 tag - Amol - 23 Sept
- [x] Version updates (only csi driver and operator versions) in 2.6 docs - Amol - 16 Sept
- [x] Verify links are working in 2.6 docs (including manifests in commands) - Ghanshyam - 19 Sept and 23 Sept
- [x] Verify the images and yaml from release branch are correct - on k8s cluster - CLI install/Upgrade (on GA date) - Saurabh - 23 Sept
